language: php

sudo: false

php:
  - 5.3.3
  - 5.3
  - 5.4
  - 5.5
  - 5.6

before_script:
  - composer self-update 1.0.0-alpha10
  - composer install --no-interaction --prefer-source

script:
  - ./vendor/bin/phpunit
